"""Single-file HTML report in the Graphite design, standard library only.

The page works offline: CSS is inline, charts are inline SVG, and there are
no scripts, web fonts or loaded resources (the only links are the sources in
the static "Why it matters" block). Every value that comes from the config,
a rule or the file name goes through ``_e`` (``html.escape``) before it
reaches the page. Templates are ``string.Template``, so a ``$`` or ``{`` in a
value is never interpreted.

The approved design lives in ``docs/design/report-graphite.html``; its CSS
is ``graphite.css`` and its static context block ``context.html``.
"""

import re
from collections import defaultdict
from functools import cache
from html import escape
from importlib.resources import files
from itertools import groupby
from string import Template

from guardian.core.models import AuditResult, Finding, References, Remediation, Severity, Status
from guardian.core.platforms import PLATFORMS
from guardian.core.reporting import sorted_findings, sorted_rules
from guardian.core.rules.engine import GLOBAL_TARGET


@cache
def _resource(name: str) -> str:
    """A file shipped next to this module, read on first use (not at import)."""
    return files("guardian.core.reporting").joinpath(name).read_text(encoding="utf-8")


SEVERITY_COLOR = {"critical": "#a4161a", "high": "#d03b3b", "medium": "#ec835a", "low": "#fab219"}
PASS_COLOR = "#0ca30c"
FAIL_COLOR = "#d03b3b"
TEXT_COLOR = "#e8e6e1"
MUTED_COLOR = "#a3a09a"

AREA_LABELS = {
    "AAA": "AAA",
    "IF": "Interfaces",
    "L2": "Layer 2",
    "LOG": "Logging",
    "MGMT": "Management access",
    "NTP": "Time / NTP",
    "PASS": "Passwords",
    "SNMP": "SNMP",
    "SVC": "Services",
}

CISCO_GUIDE_URL = "https://sec.cloudapps.cisco.com/security/center/resources/IOS_XE_hardening"
CISA_URL = (
    "https://www.cisa.gov/resources-tools/resources/"
    "enhanced-visibility-and-hardening-guidance-communications-infrastructure"
)
REFERENCES_NOTE = (
    "References: DISA STIG Cisco IOS XE (Router NDM V3R7, Router RTR V3R5, Switch L2S V3R2), "
    "NIST SP 800-53 Rev. 5, Cisco IOS XE Hardening Guide, CISA Hardening Guidance (12/2024); "
    "verified 2026-10-08. Guardian is not an official STIG scanner; the mapping is informative."
)

# A placeholder after escaping: &lt;NTP_SERVER_IP&gt;
_PLACEHOLDER = re.compile(r"&lt;[A-Z][A-Z0-9_]*&gt;")


def _e(value: object) -> str:
    """Escape any value for HTML text and attribute content."""
    return escape("" if value is None else str(value), quote=True)


_PAGE = Template("""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="color-scheme" content="dark">
<meta http-equiv="Content-Security-Policy" \
content="default-src 'none'; style-src 'unsafe-inline'; img-src data:">
<title>Guardian audit report: $name</title>
<style>
$css</style>
</head>
<body>
<main class="sheet">
<div class="conf"><span><strong>Confidential</strong> · contains device configuration \
details</span><span>Guardian $guardian_version</span></div>
<h1>Configuration audit report</h1>
<p class="sub">$name · $platform_version · $generated</p>
<dl class="meta">$meta</dl>
<h2>1. Summary</h2>
<p class="$verdict_class">$verdict</p>
<div class="two">
$summary_table
<figure>$score<figcaption style="margin-top:18px">Failed rules by severity</figcaption>\
$severity_chart</figure>
</div>
<figure style="margin-top:28px"><figcaption>Compliance by area, worst first \
(passed / evaluated)</figcaption>$area_chart<ul class="legend"><li><span class="sw" \
style="background:#d03b3b"></span>Fail</li><li><span class="sw" style="background:#0ca30c">\
</span>Pass</li></ul></figure>
<h2>2. Findings</h2>
$findings
<h2>3. Other rules</h2>
$other_rules
<h2>4. Context</h2>
$context<footer>Generated by Guardian $guardian_version from $file (SHA-256 $sha_short…). \
This report reflects the saved configuration only, not the running state of the device.<br>\
$references_note</footer>
</main>
</body>
</html>
""")

LOCKOUT_BADGE = '<span class="risk risk-lockout">&#9888; May cut your access</span>'
BOTH_ENDS_BADGE = '<span class="risk risk-ends">Change both ends</span>'

# Shown once above the findings.
_GUIDE = f"""<p>Failed rules, most severe first. Passwords, secrets, hashes and SNMP \
communities are never shown; they appear as &lt;redacted&gt;.</p>
<div class="banner guide" role="note"><p><strong>How to use the suggested changes.</strong> \
The commands are a suggestion, not a script. Review them, replace every highlighted \
<mark class="ph">&lt;PLACEHOLDER&gt;</mark> and try them in a lab first.</p>
<ul class="tips"><li>{LOCKOUT_BADGE} The change can cut your access: run \
<code>reload in 10</code> before, and <code>reload cancel</code> after you have confirmed \
you can still log in.</li>
<li>{BOTH_ENDS_BADGE} The device on the other side of the link needs the matching change \
at the same time.</li>
<li>Nothing in the suggested changes runs <code>write memory</code>. Save only after you have \
checked the result.</li>
<li>Replace placeholders in passwords too: IOS accepts \
<mark class="ph">&lt;NEW_PASSWORD&gt;</mark> as a password.</li></ul></div>
"""

_FINDING = Template("""<section class="finding">
<h3><span class="num">$number.</span><span class="sev sev-$severity">$severity_label</span>\
<span>$title</span><span class="id">$rule_id</span>$risks</h3>
<dl class="facts"><dt>Area</dt><dd>$area</dd>
<dt>Location</dt><dd class="mono">$locations</dd>
$config_lines<dt>Why it matters</dt><dd>$rationale</dd>
$references</dl>
$remediation
</section>""")


def render(result: AuditResult) -> str:
    """The whole report as one HTML document."""
    rules = sorted_rules(result)
    findings = sorted_findings(result)
    name = result.hostname or result.file
    platform = PLATFORMS.get(result.platform)
    platform_name = platform.description if platform else result.platform
    version = f"{platform_name} {result.version}" if result.version else platform_name
    generated = result.generated_at.replace("T", " ").replace("Z", " UTC")
    guardian = _short_version(result.guardian_version)

    meta = "".join(
        f'<dt>{label}</dt><dd class="{cls}">{_e(value)}</dd>'
        for label, value, cls in (
            ("Hostname", result.hostname or "unknown", ""),
            ("IOS version (from config)", result.version or "unknown", ""),
            ("Platform", platform_name, ""),
            ("Input file", result.file, "mono"),
            ("SHA-256 of input", result.sha256, "mono"),
            ("Generated", generated, ""),
            ("Guardian", guardian, ""),
        )
    )
    verdict_class, verdict = _verdict(result)
    return _PAGE.substitute(
        css=_resource("graphite.css"),
        name=_e(name),
        guardian_version=_e(guardian),
        platform_version=_e(version),
        generated=_e(generated),
        meta=meta,
        verdict_class=verdict_class,
        verdict=_e(verdict),
        summary_table=_summary_table(result),
        score=_score(result),
        severity_chart=_severity_chart(result),
        area_chart=_area_chart(result),
        findings=_findings(findings, {r.rule_id: r.references for r in result.rules}),
        references_note=REFERENCES_NOTE,
        other_rules=_other_rules(rules),
        context=_resource("context.html"),
        file=_e(result.file),
        sha_short=_e(result.sha256[:16]),
    )


def _short_version(version: str) -> str:
    """Major.minor for display ("0.1.0" -> "0.1"); the JSON keeps the full version."""
    return ".".join(version.split(".")[:2])


# ------------------------------------------------------------------ summary


def _counts(result: AuditResult) -> tuple[int, int, int]:
    """Passed, failed and N/A rules."""
    statuses = [r.status for r in result.rules]
    return (
        statuses.count(Status.PASS),
        statuses.count(Status.FAIL),
        statuses.count(Status.NOT_APPLICABLE),
    )


def _verdict(result: AuditResult) -> tuple[str, str]:
    passed, failed, _ = _counts(result)
    evaluated = passed + failed
    if not evaluated:
        return "verdict", "Nothing was checked: no rule applies to this config."
    if not failed:
        return "verdict ok", f"Compliant. All {evaluated} applicable rules passed."
    serious = sum(
        1 for r in result.rules if r.status is Status.FAIL and r.severity.rank >= Severity.HIGH.rank
    )
    return (
        "verdict",
        f"Not compliant. {failed} of {evaluated} applicable rules failed, "
        f"{serious} of them high or critical severity.",
    )


def _severities(result: AuditResult) -> list[Severity]:
    """Severities shown in tables and charts: critical only when a rule uses it."""
    used = {r.severity for r in result.rules}
    return [s for s in reversed(Severity) if s is not Severity.CRITICAL or s in used]


def _summary_table(result: AuditResult) -> str:
    rows = []
    totals = [0, 0, 0, 0]
    for severity in _severities(result):
        statuses = [r.status for r in result.rules if r.severity is severity]
        cells = [
            statuses.count(Status.FAIL),
            statuses.count(Status.PASS),
            statuses.count(Status.NOT_APPLICABLE),
            len(statuses),
        ]
        totals = [a + b for a, b in zip(totals, cells, strict=True)]
        rows.append(
            f'<tr><th scope="row"><span class="sev sev-{severity.value}">'
            f"{severity.value.capitalize()}</span></th>" + _cells(cells) + "</tr>"
        )
    rows.append('<tr class="total"><th scope="row">Total</th>' + _cells(totals) + "</tr>")
    head = "".join(
        f'<th scope="col">{h}</th>' for h in ("Severity", "Fail", "Pass", "N/A", "Rules")
    )
    return (
        f'<table class="summary"><thead><tr>{head}</tr></thead><tbody>'
        + "".join(rows)
        + "</tbody></table>"
    )


def _cells(values: list[int]) -> str:
    fail, *rest = values
    return f'<td class="n fail">{fail}</td>' + "".join(f'<td class="n">{v}</td>' for v in rest)


def _score(result: AuditResult) -> str:
    passed, failed, _ = _counts(result)
    evaluated = passed + failed
    label = f"{passed} of {evaluated} evaluated rules passed"
    number = f"{round(100 * passed / evaluated)}&nbsp;%" if evaluated else "n/a"
    parts = [(passed, PASS_COLOR, f"{passed} passed"), (failed, FAIL_COLOR, f"{failed} failed")]
    bars = _bars(320, parts, x=0, y=0, height=10, even_gap=True)
    return (
        f'<div class="score"><div class="score-num">{number}</div><div class="score-txt">'
        f"<b>compliance score</b><br>{label}</div></div>"
        f'<svg viewBox="0 0 320 10" width="100%" height="10" role="img" class="chart" '
        f'aria-label="{label}" preserveAspectRatio="none">{bars}</svg>'
        '<p class="fn">Score = passed / evaluated rules. Not applicable rules are not counted.</p>'
    )


def _bars(
    width: float,
    parts: list[tuple[int, str, str]],
    *,
    x: float,
    y: int,
    height: int,
    even_gap: bool = False,
) -> str:
    """Bars side by side, each as long as its share of ``width``.

    Two bars keep a 2px gap, as in the design: taken from the first bar, or
    1px from each with ``even_gap``. ``parts`` are (count, color, tooltip);
    empty ones are skipped.
    """
    parts = [p for p in parts if p[0]]
    total = sum(count for count, _, _ in parts)
    rects = []
    for i, (count, color, title) in enumerate(parts):
        length = width * count / total
        if len(parts) > 1:
            length -= 1 if even_gap else (2 if i == 0 else 0)
        length = max(length, 0)
        rects.append(
            f'<rect x="{x:.1f}" y="{y}" width="{length:.1f}" height="{height}" rx="3" '
            f'fill="{color}"><title>{title}</title></rect>'
        )
        x += length + 2
    return "".join(rects)


def _severity_chart(result: AuditResult) -> str:
    if not any(r.status is Status.FAIL for r in result.rules):
        return '<p class="fn">No failed rules.</p>'
    severities = _severities(result)
    failed = {
        s: sum(1 for r in result.rules if r.severity is s and r.status is Status.FAIL)
        for s in severities
    }
    unit = 382 / max(max(failed.values(), default=0), 1)
    rows = []
    for i, severity in enumerate(severities):
        y = i * 28
        length = unit * failed[severity]
        label = severity.value.capitalize()
        rows.append(
            f'<text x="0" y="{y + 13}" font-size="12" fill="{TEXT_COLOR}">{label}</text>'
            f'<rect x="70.0" y="{y}" width="{length:.1f}" height="18" rx="3" '
            f'fill="{SEVERITY_COLOR[severity.value]}"><title>{label}: {failed[severity]} '
            f"failed</title></rect>"
            f'<text x="{70 + length + 6:.1f}" y="{y + 13}" font-size="12" font-weight="600" '
            f'fill="{TEXT_COLOR}">{failed[severity]}</text>'
        )
    height = len(severities) * 28 - 10
    return (
        f'<svg viewBox="0 0 480 {height}" width="100%" role="img" class="chart" '
        f'aria-label="Failed rules by severity">' + "".join(rows) + "</svg>"
    )


def _area(rule_id: str) -> str:
    """The AREA part of PLATFORM-AREA-NNN, or the whole id for other formats."""
    parts = rule_id.split("-")
    return parts[1] if len(parts) >= 3 else rule_id


def _area_chart(result: AuditResult) -> str:
    areas: dict[str, list[int]] = defaultdict(lambda: [0, 0])  # area -> [passed, failed]
    for rule in result.rules:
        if rule.status is Status.PASS:
            areas[_area(rule.rule_id)][0] += 1
        elif rule.status is Status.FAIL:
            areas[_area(rule.rule_id)][1] += 1
    # Worst first: lowest pass ratio, then the bigger area, then by code.
    order = sorted(
        ((area, p, f) for area, (p, f) in areas.items()),
        key=lambda item: (item[1] / (item[1] + item[2]), -(item[1] + item[2]), item[0]),
    )
    rows = []
    for i, (area, passed, failed) in enumerate(order):
        y = i * 25
        code, total = _e(area), passed + failed
        parts = [
            (failed, FAIL_COLOR, f"{code}: {failed} of {total} failed"),
            (passed, PASS_COLOR, f"{code}: {passed} of {total} passed"),
        ]
        rows.append(
            f'<text x="0" y="{y + 12}" font-size="12" fill="{TEXT_COLOR}">'
            f"{_e(AREA_LABELS.get(area, area))}</text>"
            + _bars(546, parts, x=170.0, y=y, height=16)
            + f'<text x="724" y="{y + 12}" font-size="11.5" fill="{MUTED_COLOR}">'
            f"{passed}/{total}</text>"
        )
    height = max(len(order) * 25 - 9, 0)
    return (
        f'<svg viewBox="0 0 760 {height}" width="100%" role="img" class="chart" '
        f'aria-label="Compliance by area, worst first">' + "".join(rows) + "</svg>"
    )


# ----------------------------------------------------------------- findings


def _findings(findings: list[Finding], references: dict[str, References]) -> str:
    if not findings:
        return '<p class="none">No findings. Every applicable rule passed.</p>'
    groups = groupby(findings, key=lambda f: f.rule_id)
    sections = [
        _finding(n, list(group), references) for n, (_, group) in enumerate(groups, start=1)
    ]
    return _GUIDE + "".join(sections)


def _finding(number: int, group: list[Finding], references: dict[str, References]) -> str:
    first = group[0]
    area = _area(first.rule_id)
    locations = _unique(f.location or f.target for f in group)
    lines = [f.target for f in group if f.target not in (f.location, GLOBAL_TARGET)]
    remediation = _merge([f.remediation for f in group if f.remediation])
    config_lines = ""
    if lines:
        shown = "<br>".join(_e(line) for line in lines)
        config_lines = f'<dt>Config line</dt><dd class="mono">{shown}</dd>\n'
    return _FINDING.substitute(
        number=number,
        severity=_e(first.severity.value),
        severity_label=_e(first.severity.value.capitalize()),
        title=_e(first.title),
        rule_id=_e(first.rule_id),
        area=_e(f"{AREA_LABELS.get(area, area)} ({area})"),
        locations=", ".join(_e(location) for location in locations),
        config_lines=config_lines,
        rationale=_e(first.rationale),
        references=_references(references.get(first.rule_id, References())),
        risks=_risks(remediation),
        remediation=_remediation(remediation),
    )


def _references(refs: References) -> str:
    """The References row of a finding; empty when the rule has no references."""
    tags = []
    for stig in refs.stig:
        text = f"STIG {stig.id} · {stig.severity}"
        if stig.relation == "related":
            text = "Related to " + text
        tags.append(f'<span class="ref">{_e(text)}</span>')
    tags += [f'<span class="ref">{_e("NIST " + c)}</span>' for c in refs.nist_800_53]
    if refs.cisco_guide:
        text = _e("Cisco Hardening Guide: " + refs.cisco_guide)
        tags.append(f'<a class="ref" rel="noreferrer" href="{CISCO_GUIDE_URL}">{text}</a>')
    if refs.cisa:
        tags.append(f'<a class="ref" rel="noreferrer" href="{CISA_URL}">CISA 2024</a>')
    if not tags:
        return ""
    return f'<dt>References</dt><dd class="refs">{" ".join(tags)}</dd>'


def _unique(values) -> list:
    return list(dict.fromkeys(values))


def _is_global(commands: tuple[str, ...], i: int) -> bool:
    """A top-level command that does not open a block (no indented line after it)."""
    if commands[i].startswith(" "):
        return False
    return i + 1 == len(commands) or not commands[i + 1].startswith(" ")


def _merge(remediations: list[Remediation]) -> Remediation | None:
    """One remediation for all places a rule failed.

    Each place's commands appear once; global commands (``ip ssh version 2``)
    appear once even when several blocks need them.
    """
    if not remediations:
        return None
    first = remediations[0]
    commands: list[str] = []
    seen_global: set[str] = set()
    for cs in _unique(r.recommended_change for r in remediations):
        for i, command in enumerate(cs):
            if _is_global(cs, i):
                if command in seen_global:
                    continue
                seen_global.add(command)
            commands.append(command)
    return Remediation(
        recommended_change=tuple(commands),
        before_you_apply=tuple(_unique(t for r in remediations for t in r.before_you_apply)),
        notes=tuple(_unique(t for r in remediations for t in r.notes)),
        if_service_needed=first.if_service_needed,
        may_cut_access=first.may_cut_access,
        change_both_ends=first.change_both_ends,
    )


def _placeholders(escaped: str) -> str:
    """Highlight <PLACEHOLDERS> in text that is already escaped."""
    return _PLACEHOLDER.sub(lambda m: f'<mark class="ph">{m.group(0)}</mark>', escaped)


def _text(value: str) -> str:
    """Prose from a rule: escaped first, then `code` and <PLACEHOLDERS> marked up."""
    return _placeholders(re.sub(r"`([^`]+)`", r"<code>\1</code>", _e(value)))


def _commands(commands: tuple[str, ...]) -> str:
    """Commands as a <pre> block with highlighted placeholders."""
    return "<pre>" + _placeholders(_e("\n".join(commands))) + "</pre>"


def _risks(r: Remediation | None) -> str:
    """Risk badges for the finding heading."""
    if r is None:
        return ""
    badges = [LOCKOUT_BADGE] if r.may_cut_access else []
    badges += [BOTH_ENDS_BADGE] if r.change_both_ends else []
    return "".join(badges)


def _remediation(r: Remediation | None) -> str:
    if r is None:
        return ""
    notes = "".join(f'<p class="fix-note">{_text(n)}</p>' for n in r.notes)
    sections = [
        f"<section><h4>Recommended change</h4>{_commands(r.recommended_change)}{notes}</section>"
    ]
    if r.before_you_apply:
        checks = "".join(f"<li>{_text(t)}</li>" for t in r.before_you_apply)
        sections.append(
            f'<section><h4>Before you apply</h4><ul class="checks">{checks}</ul></section>'
        )
    if r.if_service_needed:
        alt = r.if_service_needed
        commands = _commands(alt.commands) if alt.commands else ""
        sections.append(
            "<section><h4>If the service is needed</h4>"
            f'<p class="alt">{_text(alt.text)}</p>{commands}</section>'
        )
    return '<div class="fix">' + "".join(sections) + "</div>"


# -------------------------------------------------------------- other rules


def _other_rules(rules) -> str:
    na = [r for r in rules if r.status is Status.NOT_APPLICABLE]
    passed = [r for r in rules if r.status is Status.PASS]
    na_items = "".join(
        f"<li><code>{_e(r.rule_id)}</code> {_e(r.title)}<br>"
        f'<span class="why">{_e(r.reason)}</span></li>'
        for r in na
    )
    passed_items = "".join(f"<li><code>{_e(r.rule_id)}</code> {_e(r.title)}</li>" for r in passed)
    return (
        f'<details class="appendix"><summary>Not applicable ({len(na)})</summary>'
        f'<ul class="na">{na_items}</ul></details>\n'
        f'<details class="appendix"><summary>Passed ({len(passed)})</summary>'
        f'<ul class="passed">{passed_items}</ul></details>'
    )
